rsvplist.settings:
  type: config_object
  label: RSVP List Content Type rsvplist.settings

  mapping:
    allowed_types:
      type: sequence
      label: Content types the RSVP Form can desplay on
      sequence:
        type: string
        label: Content type